### ISSUE TITLE
Server Issues.

### ISSUE THREAD

**Issue by joeyboli** [pfrlv/plofier-web#3]
hey joey here again, we are currently facing issues with our main server,

what happened, we use Azuracast and today we tried upgrading the server but after the upgrade, it seems the Mysql server is not responding. there might be irregularities in the stream like Gateway error issues.

issue screenshot url :  https://bedrive.streamafrica.net/drive/s/hDFj4MI24h3Fp6TLe9914S6pqFhCqO

**Comment by pfrlv** [comment]
Oh sorry, good luck with the problem
